"""Initial migration

Revision ID: 8f4b79e09d1f
Revises: 
Create Date: 2025-10-27 09:13:15.390439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f4b79e09d1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lifestyle_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disease_type', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('recommendation_text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disease_type', 'risk_level', 'category', 'recommendation_text')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('abha_id', sa.String(length=14), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('state_name', sa.String(length=100), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abha_id')
    )
    op.create_table('consultations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('consultation_type', sa.String(length=50), nullable=False),
    sa.Column('consultation_datetime', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diabetes_assessments',
    sa.Column('pregnancies', sa.Integer(), nullable=False),
    sa.Column('glucose', sa.Float(), nullable=False),
    sa.Column('blood_pressure', sa.Float(), nullable=False),
    sa.Column('skin_thickness', sa.Float(), nullable=False),
    sa.Column('insulin', sa.Float(), nullable=False),
    sa.Column('diabetes_pedigree_function', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('heart_assessments',
    sa.Column('chest_pain_type', sa.Integer(), nullable=False),
    sa.Column('resting_blood_pressure', sa.Float(), nullable=False),
    sa.Column('cholesterol', sa.Float(), nullable=False),
    sa.Column('fasting_blood_sugar', sa.Integer(), nullable=False),
    sa.Column('resting_ecg', sa.Integer(), nullable=False),
    sa.Column('max_heart_rate', sa.Float(), nullable=False),
    sa.Column('exercise_angina', sa.Integer(), nullable=False),
    sa.Column('st_depression', sa.Float(), nullable=False),
    sa.Column('st_slope', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('liver_assessments',
    sa.Column('total_bilirubin', sa.Float(), nullable=False),
    sa.Column('direct_bilirubin', sa.Float(), nullable=False),
    sa.Column('alkaline_phosphotase', sa.Float(), nullable=False),
    sa.Column('alamine_aminotransferase', sa.Float(), nullable=False),
    sa.Column('aspartate_aminotransferase', sa.Float(), nullable=False),
    sa.Column('total_proteins', sa.Float(), nullable=False),
    sa.Column('albumin', sa.Float(), nullable=False),
    sa.Column('globulin', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('mental_health_assessments',
    sa.Column('phq_score', sa.Integer(), nullable=False),
    sa.Column('gad_score', sa.Integer(), nullable=False),
    sa.Column('sleep_quality', sa.Integer(), nullable=False),
    sa.Column('mood_factors', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('risk_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('diabetes_score', sa.Float(), nullable=True),
    sa.Column('diabetes_level', sa.String(length=20), nullable=True),
    sa.Column('liver_score', sa.Float(), nullable=True),
    sa.Column('liver_level', sa.String(length=20), nullable=True),
    sa.Column('heart_score', sa.Float(), nullable=True),
    sa.Column('heart_level', sa.String(length=20), nullable=True),
    sa.Column('mental_health_score', sa.Float(), nullable=True),
    sa.Column('mental_health_level', sa.String(length=20), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('predicted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_predictions')
    op.drop_table('mental_health_assessments')
    op.drop_table('liver_assessments')
    op.drop_table('heart_assessments')
    op.drop_table('diabetes_assessments')
    op.drop_table('consultations')
    op.drop_table('patients')
    op.drop_table('users')
    op.drop_table('lifestyle_recommendations')
    # ### end Alembic commands ###
